import { FlowType, SourceItem, FlowLane, FlowNode, FlowEdge, FlowChain, BottleneckItem, LayerTimingItem, ApprovalFrictionItem, OptimizationOption, FlowTraceMockData } from './types';

export const MOCK_FLOW_DATA: FlowTraceMockData = {
  event: {
    eventId: 'evt_almaty_321',
    title: 'Almaty Collision / 3.21',
    location: 'Al-Farabi Ave, Almaty',
    startedAt: '2026-03-21T03:05:00Z',
    endedAt: '2026-03-21T18:30:00Z',
    flowMode: 'POST',
  },
  kpis: [
    { key: 'source_items', label: 'Intelligence Items', value: 128, trend: 'up', tone: 'default' },
    { key: 'systems', label: 'Involved Systems', value: 14, tone: 'default' },
    { key: 'total_time', label: 'Total Flow Time', value: '15h 25m', tone: 'warning' },
    { key: 'bottleneck', label: 'Longest Bottleneck', value: '3h 12m', tone: 'danger' },
    { key: 'escalation', label: 'Escalation Level', value: 'Ministerial', tone: 'warning' },
    { key: 'unresolved', label: 'Unresolved Delays', value: 3, tone: 'danger' },
  ],
  lanes: [
    { id: 'lane_external', label: 'External Signals', order: 1, type: 'external' },
    { id: 'lane_analyst', label: 'Duty Analyst', order: 2, type: 'analysis' },
    { id: 'lane_district', label: 'District Police', order: 3, type: 'district' },
    { id: 'lane_municipal', label: 'Municipal Police', order: 4, type: 'municipal' },
    { id: 'lane_provincial', label: 'Provincial Level', order: 5, type: 'provincial' },
    { id: 'lane_ministerial', label: 'Ministerial Workbench', order: 6, type: 'ministerial' },
  ],
  sources: [
    {
      id: 'src_tg_001',
      category: 'social',
      sourceType: 'Telegram Image',
      title: 'Al-Farabi Ave Crash Photos',
      firstSeenAt: '2026-03-21T03:08:00Z',
      extractedSignal: 'Major accident, police car involved',
      confidence: 'high',
      enteredVia: 'OSINT Monitoring Station',
      chainId: 'chain_social_01',
      tags: ['Accident', 'Police', 'Almaty'],
    },
    {
      id: 'src_call_001',
      category: 'internal',
      sourceType: 'Emergency Call',
      title: '102 Alarm #87736780',
      firstSeenAt: '2026-03-21T03:05:00Z',
      extractedSignal: 'High-speed collision, multiple fatalities',
      confidence: 'verified',
      enteredVia: 'District Dispatch Center',
      chainId: 'chain_internal_01',
      tags: ['Emergency', 'Fatality'],
    },
    {
      id: 'src_web_001',
      category: 'web',
      sourceType: 'News Portal',
      title: 'TengriNews: Traffic Blockage',
      firstSeenAt: '2026-03-21T03:25:00Z',
      extractedSignal: 'Public outcry over police response',
      confidence: 'medium',
      enteredVia: 'Web Crawler',
      chainId: 'chain_web_01',
      tags: ['News', 'Public Protest'],
    },
  ],
  nodes: [
    // Social Media Chain
    {
      id: 'node_social_01',
      chainId: 'chain_social_01',
      laneId: 'lane_external',
      title: 'Telegram Discovery',
      enterAt: '2026-03-21T03:08:00Z',
      exitAt: '2026-03-21T03:10:00Z',
      durationMs: 120000,
      owner: 'OSINT-Bot-01',
      action: 'Signal Extraction',
      status: 'completed',
      approvalCount: 0,
      systemName: 'Aegis OSINT',
      sourceIds: ['src_tg_001'],
      outputNodeIds: ['node_social_02'],
    },
    {
      id: 'node_social_02',
      chainId: 'chain_social_01',
      laneId: 'lane_analyst',
      title: 'Analyst Verification',
      enterAt: '2026-03-21T03:10:00Z',
      exitAt: '2026-03-21T03:45:00Z',
      durationMs: 2100000,
      owner: 'U-101 (Karlee)',
      action: 'Manual Verification',
      status: 'completed',
      approvalCount: 1,
      systemName: 'Analyst Workbench',
      sourceIds: ['src_tg_001'],
      outputNodeIds: ['node_social_03'],
    },
    {
      id: 'node_social_03',
      chainId: 'chain_social_01',
      laneId: 'lane_district',
      title: 'District Warning',
      enterAt: '2026-03-21T03:45:00Z',
      exitAt: '2026-03-21T04:15:00Z',
      durationMs: 1800000,
      owner: 'D-Dispatch-01',
      action: 'Internal Notification',
      status: 'completed',
      approvalCount: 1,
      systemName: 'CAD-Internal System',
      sourceIds: ['src_tg_001'],
      outputNodeIds: ['node_social_04'],
    },
    {
      id: 'node_social_04',
      chainId: 'chain_social_01',
      laneId: 'lane_municipal',
      title: 'Municipal Review',
      enterAt: '2026-03-21T04:15:00Z',
      exitAt: '2026-03-21T07:30:00Z',
      durationMs: 11700000,
      owner: 'M-Workbench-03',
      action: 'Case Summary',
      status: 'delayed',
      approvalCount: 2,
      systemName: 'Case Management System',
      delayReason: 'Sensitive content requires repeated approval',
      isBottleneck: true,
      sourceIds: ['src_tg_001'],
      outputNodeIds: ['node_social_05'],
    },
    {
      id: 'node_social_05',
      chainId: 'chain_social_01',
      laneId: 'lane_provincial',
      title: 'Provincial Briefing',
      enterAt: '2026-03-21T07:30:00Z',
      exitAt: '2026-03-21T09:00:00Z',
      durationMs: 5400000,
      owner: 'P-Director',
      action: 'Executive Summary',
      status: 'completed',
      approvalCount: 1,
      systemName: 'Executive Dashboard',
      sourceIds: ['src_tg_001'],
      outputNodeIds: [],
    },
  ],
  edges: [
    { id: 'edge_01', chainId: 'chain_social_01', source: 'node_social_01', target: 'node_social_02', relation: 'forwarded' },
    { id: 'edge_02', chainId: 'chain_social_01', source: 'node_social_02', target: 'node_social_03', relation: 'reviewed' },
    { id: 'edge_03', chainId: 'chain_social_01', source: 'node_social_03', target: 'node_social_04', relation: 'escalated', isCriticalPath: true },
    { id: 'edge_04', chainId: 'chain_social_01', source: 'node_social_04', target: 'node_social_05', relation: 'escalated', isCriticalPath: true },
  ],
  chains: [
    {
      id: 'chain_social_01',
      name: 'Social Media Flow (Telegram)',
      type: 'social',
      sourceId: 'src_tg_001',
      startAt: '2026-03-21T03:08:00Z',
      endAt: '2026-03-21T09:00:00Z',
      totalDurationMs: 21120000,
      escalationLevel: 'Provincial Level',
      nodeIds: ['node_social_01', 'node_social_02', 'node_social_03', 'node_social_04', 'node_social_05'],
      edgeIds: ['edge_01', 'edge_02', 'edge_03', 'edge_04'],
      status: 'completed',
    },
  ],
  bottlenecks: [
    {
      nodeId: 'node_social_04',
      label: 'Municipal Review',
      laneLabel: 'Municipal Police',
      durationMs: 11700000,
      reason: 'Sensitive media content requires repeated manual approval',
      savingsPotentialMs: 7200000,
      severity: 'high',
    },
    {
      nodeId: 'node_social_02',
      label: 'Analyst Verification',
      laneLabel: 'Duty Analyst',
      durationMs: 2100000,
      reason: 'Requires manual cross-comparison with CAD logs',
      savingsPotentialMs: 1200000,
      severity: 'medium',
    },
  ],
  layerTimings: [
    { laneId: 'lane_external', laneLabel: 'External Signals', totalMs: 120000, avgMs: 120000, maxMs: 120000, count: 1 },
    { laneId: 'lane_analyst', laneLabel: 'Duty Analyst', totalMs: 2100000, avgMs: 2100000, maxMs: 2100000, count: 1 },
    { laneId: 'lane_district', laneLabel: 'District Police', totalMs: 1800000, avgMs: 1800000, maxMs: 1800000, count: 1 },
    { laneId: 'lane_municipal', laneLabel: 'Municipal Police', totalMs: 11700000, avgMs: 11700000, maxMs: 11700000, count: 1 },
    { laneId: 'lane_provincial', laneLabel: 'Provincial Level', totalMs: 5400000, avgMs: 5400000, maxMs: 5400000, count: 1 },
  ],
  repeatedApprovals: [
    { label: 'Municipal Case Summary', laneLabel: 'Municipal Police', approvalCount: 2, extraDelayMs: 3600000 },
    { label: 'District Notification', laneLabel: 'District Police', approvalCount: 1, extraDelayMs: 600000 },
  ],
  optimizationOptions: [
    { id: 'opt_auto_verify', label: 'AI Auto Verification', description: 'Skip manual analyst verification for high-confidence signals', enabled: false, estimatedSavingsMs: 1800000 },
    { id: 'opt_single_approval', label: 'Single-Level Approval', description: 'Cancel redundant municipal review for verified district reports', enabled: false, estimatedSavingsMs: 7200000 },
    { id: 'opt_direct_escalation', label: 'Direct Provincial Escalation', description: 'Allow critical signals to bypass municipal workbench', enabled: false, estimatedSavingsMs: 10800000 },
  ],
  reportingData: {
    kpis: [
      { key: 'level', label: 'Current Escalation Level', value: 'Ministerial', tone: 'default' },
      { key: 'total_time', label: 'Total Escalation Time', value: '31h 45m', tone: 'warning' },
      { key: 'bottleneck', label: 'Longest Bottleneck', value: 'Provincial Prep', tone: 'danger' },
      { key: 'returns', label: 'Return Count', value: '1', tone: 'danger' },
      { key: 'approvals', label: 'Approval Count', value: '9', tone: 'success' },
      { key: 'status', label: 'Final Status', value: 'Archived', tone: 'success' },
    ],
    zones: [
      {
        id: 'zone_trigger',
        title: 'Trigger Escalation',
        subtitle: 'Trigger Escalation',
        order: 1,
        cards: [
          {
            id: 'card_trigger_1',
            zoneId: 'zone_trigger',
            title: 'Trigger Report',
            owner: 'System Auto Trigger',
            status: 'completed',
            totalDurationLabel: '14h 50m',
            totalDurationMs: 14 * 3600000 + 50 * 60000,
            isDetailed: true,
            steps: [
              { id: 's1', label: 'Warning Threshold Reached', status: 'completed', durationLabel: '18m', durationMs: 18 * 60000 },
              { id: 's2', label: 'Multiple Casualties Involved', status: 'completed', durationLabel: '42m', durationMs: 42 * 60000 },
              { id: 's3', label: 'Sentiment Heat Exceeded', status: 'completed', durationLabel: '1h 10m', durationMs: 70 * 60000 },
              { id: 's4', label: 'Sensitive Area/Group Involved', status: 'waiting', durationLabel: '35m', durationMs: 35 * 60000 },
              { id: 's5', label: 'Superior Attention Request', status: 'completed', durationLabel: '12h 5m', durationMs: 725 * 60000 },
            ]
          }
        ]
      },
      {
        id: 'zone_district',
        title: 'District Level',
        subtitle: 'District Level',
        order: 2,
        cards: [
          {
            id: 'card_dist_1',
            zoneId: 'zone_district',
            title: 'Escalation Prep',
            owner: 'District Duty Room',
            status: 'delayed',
            totalDurationLabel: '5h 00m',
            totalDurationMs: 5 * 3600000,
            isDetailed: true,
            steps: [
              { id: 'ds1', label: 'Collect Raw Materials', status: 'completed', durationLabel: '45m', durationMs: 45 * 60000 },
              { id: 'ds2', label: 'Fill Template Fields', status: 'completed', durationLabel: '30m', durationMs: 30 * 60000 },
              { id: 'ds3', label: 'Organize Evidence Attachments', status: 'delayed', durationLabel: '2h 15m', durationMs: 135 * 60000 },
              { id: 'ds4', label: 'Draft Summary', status: 'completed', durationLabel: '1h 05m', durationMs: 65 * 60000 },
              { id: 'ds5', label: 'Optimize Escalation Statement', status: 'waiting', durationLabel: '25m', durationMs: 25 * 60000 },
            ]
          },
          {
            id: 'card_dist_2',
            zoneId: 'zone_district',
            title: 'Level Audit',
            owner: 'District Command Group',
            status: 'delayed',
            totalDurationLabel: '5h 55m',
            totalDurationMs: 5 * 3600000 + 55 * 60000,
            isDetailed: true,
            steps: [
              { id: 'dr1', label: 'Duty Chief Audit', status: 'completed', durationLabel: '35m', durationMs: 35 * 60000 },
              { id: 'dr2', label: 'Section Chief Issue', status: 'completed', durationLabel: '1h 10m', durationMs: 70 * 60000 },
              { id: 'dr3', label: 'Command Center Confirmation', status: 'delayed', durationLabel: '3h 20m', durationMs: 200 * 60000 },
              { id: 'dr4', label: 'Align Unified Statement', status: 'waiting', durationLabel: '50m', durationMs: 50 * 60000 },
            ]
          },
          {
            id: 'card_dist_3',
            zoneId: 'zone_district',
            title: 'Escalation Send',
            owner: 'District Command Group',
            status: 'completed',
            totalDurationLabel: '1h 20m',
            totalDurationMs: 80 * 60000,
            summaryItems: ['System Push', 'Intranet Submission', 'Phone Backup', 'Dedicated Line Sync']
          },
          {
            id: 'card_dist_4',
            zoneId: 'zone_district',
            title: 'Escalation Feedback',
            owner: 'District Duty Room',
            status: 'rejected',
            totalDurationLabel: '12h 00m',
            totalDurationMs: 12 * 3600000,
            returnReason: 'Missing evidence and inconsistent summary',
            lostTimeLabel: '12h'
          }
        ]
      },
      {
        id: 'zone_municipal',
        title: 'Municipal Level',
        subtitle: 'Municipal Level',
        order: 3,
        cards: [
          { id: 'card_muni_1', zoneId: 'zone_municipal', title: 'Escalation Prep', owner: 'Municipal Intelligence Center', status: 'completed', totalDurationLabel: '2h 10m', totalDurationMs: 130 * 60000 },
          { id: 'card_muni_2', zoneId: 'zone_municipal', title: 'Level Audit', owner: 'Municipal Command', status: 'completed', totalDurationLabel: '1h 45m', totalDurationMs: 105 * 60000 },
          { id: 'card_muni_3', zoneId: 'zone_municipal', title: 'Escalation Send', owner: 'Municipal Command', status: 'completed', totalDurationLabel: '40m', totalDurationMs: 40 * 60000 },
          { id: 'card_muni_4', zoneId: 'zone_municipal', title: 'Escalation Feedback', owner: 'Municipal Intelligence Center', status: 'completed', totalDurationLabel: '25m', totalDurationMs: 25 * 60000 },
        ]
      },
      {
        id: 'zone_provincial',
        title: 'Provincial Level',
        subtitle: 'Provincial Level',
        order: 4,
        cards: [
          { 
            id: 'card_prov_1', 
            zoneId: 'zone_provincial', 
            title: 'Escalation Prep', 
            owner: 'Provincial Analysis Group', 
            status: 'delayed', 
            totalDurationLabel: '4h 30m', 
            totalDurationMs: 270 * 60000,
            delayReason: 'Return to District for Supplementary Materials',
            lostTimeLabel: '12h'
          },
          { id: 'card_prov_2', zoneId: 'zone_provincial', title: 'Level Audit', owner: 'Provincial Command Center', status: 'completed', totalDurationLabel: '2h 20m', totalDurationMs: 140 * 60000 },
          { id: 'card_prov_3', zoneId: 'zone_provincial', title: 'Escalation Send', owner: 'Provincial Command Center', status: 'completed', totalDurationLabel: '50m', totalDurationMs: 50 * 60000 },
          { id: 'card_prov_4', zoneId: 'zone_provincial', title: 'Escalation Feedback', owner: 'Provincial Analysis Group', status: 'completed', totalDurationLabel: '1h 15m', totalDurationMs: 75 * 60000 },
        ]
      },
      {
        id: 'zone_ministerial',
        title: 'Ministerial Level',
        subtitle: 'Ministerial Level',
        order: 5,
        cards: [
          { id: 'card_min_1', zoneId: 'zone_ministerial', title: 'Escalation Prep', owner: 'Ministerial Analysis Center', status: 'completed', totalDurationLabel: '1h 30m', totalDurationMs: 90 * 60000 },
          { id: 'card_min_2', zoneId: 'zone_ministerial', title: 'Level Audit', owner: 'Ministerial Command Bureau', status: 'completed', totalDurationLabel: '1h 05m', totalDurationMs: 65 * 60000 },
          { id: 'card_min_3', zoneId: 'zone_ministerial', title: 'Escalation Send', owner: 'Ministerial Command Bureau', status: 'completed', totalDurationLabel: '20m', totalDurationMs: 20 * 60000 },
          { id: 'card_min_4', zoneId: 'zone_ministerial', title: 'Escalation Feedback', owner: 'Ministerial Analysis Center', status: 'completed', totalDurationLabel: '35m', totalDurationMs: 35 * 60000 },
        ]
      },
      {
        id: 'zone_archive',
        title: 'Completed / Archive',
        subtitle: 'Completed / Archive',
        order: 6,
        cards: [
          { id: 'card_arch_1', zoneId: 'zone_archive', title: 'Process Completed', owner: 'System Archive', status: 'completed', totalDurationLabel: '15m', totalDurationMs: 15 * 60000 },
          { id: 'card_arch_2', zoneId: 'zone_archive', title: 'Record Registration', owner: 'Record Management Center', status: 'completed', totalDurationLabel: '10m', totalDurationMs: 10 * 60000 },
        ]
      }
    ],
    connections: [
      { id: 'c1', sourceCardId: 'card_trigger_1', targetCardId: 'card_dist_1', type: 'forward', tone: 'neutral' },
      { id: 'c2', sourceCardId: 'card_dist_3', targetCardId: 'card_muni_1', type: 'forward', tone: 'neutral' },
      { id: 'c3', sourceCardId: 'card_muni_3', targetCardId: 'card_prov_1', type: 'forward', tone: 'neutral' },
      { id: 'c4', sourceCardId: 'card_prov_3', targetCardId: 'card_min_1', type: 'forward', tone: 'neutral' },
      { id: 'c5', sourceCardId: 'card_min_4', targetCardId: 'card_arch_1', type: 'forward', tone: 'neutral' },
      // Reverse connection
      { id: 'c_rev_1', sourceCardId: 'card_prov_1', targetCardId: 'card_dist_4', type: 'reverse', label: 'Return Supplementary Materials', durationLabel: '12h lost', tone: 'danger' },
    ]
  }
};
